---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-configmap
  labels:
    project: prom-test
data:
  prometheus.yml: |
    global:
      scrape_interval:     10s
    scrape_configs:
      - job_name: 'starevent-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: replace
            target_label: app_kubernetes_io_name
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_version]
            action: replace
            target_label: app_kubernetes_io_version
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    project: prom-test
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
    project: prom-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
        project: prom-test
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.21.0
        ports:
        - containerPort: 9090
        volumeMounts:
        #volume mount for prometheus config
          - name: prom-config
            mountPath: "/etc/prometheus"
            readOnly: true
      volumes:
        - name: prom-config
          configMap:
            name: prom-configmap
            items:
              - key: "prometheus.yml"
                path: "prometheus.yml"