apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-configmap
  labels:
    project: prom-test
data:
  prometheus.yml: |
    global:
      scrape_interval:     10s
    scrape_configs:
      - job_name: 'starevent-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: replace
            target_label: app_kubernetes_io_name
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_version]
            action: replace
            target_label: app_kubernetes_io_version