kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database
  labels:
    project: mysql-test
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: my-volume