apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: eck
spec:
  version: 8.0.0
  podTemplate:
    spec:
      containers:
      - name: kibana
#        env:
#          - name: NODE_OPTIONS
#            value: "--max-old-space-size=2048"
#        resources:
#          requests:
#            memory: 1Gi
#            cpu: 0.5
#          limits:
#            memory: 2.5Gi
#            cpu: 2